export const SubmissionRunStatus = {
  NONE: 'NONE',
  RECEIVED: 'RECEIVED',
  COMPILING: 'COMPILING',
  COMPILED: 'COMPILED',
  COMPILATION_ERROR: 'COMPILATION_ERROR',
  FETCHING_TEST_CASES: 'FETCHING_TEST_CASES',
  RUNNING_TEST_CASE: 'RUNNING_TEST_CASE',
  RUNNING_TEST_CASES: 'RUNNING_TEST_CASES',
  RUNNING_SAMPLE_TEST_CASES: 'RUNNING_SAMPLE_TEST_CASES',
  EXECUTED_TEST_CASE: 'EXECUTED_TEST_CASE',
  FAILED_TEST_CASE: 'FAILED_TEST_CASE',
  JUDGING_TEST_CASE: 'JUDGING_TEST_CASE',
  GRADING: 'GRADING',
  FAILED: 'FAILED',
  COMPLETED: 'COMPLETED',
} as const;

export type SubmissionRunStatus = (typeof SubmissionRunStatus)[keyof typeof SubmissionRunStatus];
