export enum PrivateHandlerEventType {
  PING = 'PING',
  STORE_REMOVE_CONNECTION = 'STORE_REMOVE_CONNECTION',
  REMOVE_ECS_TASK = 'REMOVE_ECS_TASK',
  CONTINUE_CHECKING_ECS_TASKS = 'CONTINUE_CHECKING_ECS_TASKS',
  EC2_CHECK_INSTANCES = 'EC2_CHECK_INSTANCES',
  EC2_CLEAR_INSTANCES = 'EC2_CLEAR_INSTANCES',
  SAVE_PROBLEM_STATEMENT_CRAWLED = 'SAVE_PROBLEM_STATEMENT_CRAWLED',
  SAVE_PROBLEM_LANGUAGES_CRAWLED = 'SAVE_PROBLEM_LANGUAGES_CRAWLED',
  SAVE_SUBMISSION_CRAWLED = 'SAVE_SUBMISSION_CRAWLED',
  JUDGING = 'JUDGING',
  VIRTUAL_SUBMISSION = 'VIRTUAL_SUBMISSION',
  LOG_DATA = 'LOG_DATA',
}
