import type { CodeLanguage } from './commons';

export enum ErrorCode {
  // General errors
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  // UI general errors
  ABORTED_REQUEST = 'ABORTED_REQUEST',
  ERROR_ON_RESPONSE = 'ERROR_ON_RESPONSE',
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  // Company errors
  INTERNAL_SERVER_ERROR_ON_COMPANY_SERVICE = 'INTERNAL_SERVER_ERROR_ON_COMPANY_SERVICE',
  COMPANY_NOT_CREATED = 'COMPANY_NOT_CREATED',
  COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
  COMPANY_NOT_UPDATED = 'COMPANY_NOT_UPDATED',
  COMPANY_NOT_DELETED = 'COMPANY_NOT_DELETED',
  NOT_ALLOWED_TO_CREATE_THE_COMPANY = 'NOT_ALLOWED_TO_CREATE_THE_COMPANY',
  NOT_ALLOWED_TO_VIEW_THE_COMPANY = 'NOT_ALLOWED_TO_VIEW_THE_COMPANY',
  NOT_ALLOWED_TO_UPDATE_THE_COMPANY = 'NOT_ALLOWED_TO_UPDATE_THE_COMPANY',
  NOT_ALLOWED_TO_DELETE_THE_COMPANY = 'NOT_ALLOWED_TO_DELETE_THE_COMPANY',
  // User errors
  INTERNAL_SERVER_ERROR_ON_USERS_SERVICE = 'INTERNAL_SERVER_ERROR_ON_USERS_SERVICE',
  USER_NOT_CREATED = 'USER_NOT_CREATED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_UPDATED = 'USER_NOT_UPDATED',
  USER_NOT_DELETED = 'USER_NOT_DELETED',
  NOT_ALLOWED_TO_CREATE_THE_USER = 'NOT_ALLOWED_TO_CREATE_THE_USER',
  NOT_ALLOWED_TO_VIEW_THE_USER = 'NOT_ALLOWED_TO_VIEW_THE_USER',
  NOT_ALLOWED_TO_UPDATE_THE_USER = 'NOT_ALLOWED_TO_UPDATE_THE_USER',
  NOT_ALLOWED_TO_DELETE_THE_USER = 'NOT_ALLOWED_TO_DELETE_THE_USER',
  USER_IS_REPORTED = 'USER_IS_REPORTED',
  USER_IS_ARCHIVED = 'USER_IS_ARCHIVED',
  USER_WITH_EMAIL_REQUESTED_NOT_FOUND = 'USER_WITH_EMAIL_REQUESTED_NOT_FOUND',
  USER_WITH_NICKNAME_REQUESTED_NOT_FOUND = 'USER_WITH_NICKNAME_REQUESTED_NOT_FOUND',
  THE_EMAIL_IS_ALREADY_REGISTERED = 'THE_EMAIL_IS_ALREADY_REGISTERED',
  THE_NICKNAME_IS_ALREADY_TAKEN = 'THE_NICKNAME_IS_ALREADY_TAKEN',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  USER_SESSION_NOT_CREATED = 'USER_SESSION_NOT_CREATED',
  USER_SESSION_NOT_FOUND = 'USER_SESSION_NOT_FOUND',
  USER_SESSION_NOT_UPDATED = 'USER_SESSION_NOT_UPDATED',
  USER_SESSION_NOT_DELETED = 'USER_SESSION_NOT_DELETED',
  // Problem errors
  INTERNAL_SERVER_ERROR_ON_PROBLEMS_SERVICE = 'INTERNAL_SERVER_ERROR_ON_PROBLEMS_SERVICE',
  PROBLEM_NOT_CREATED = 'PROBLEM_NOT_CREATED',
  PROBLEM_NOT_FOUND = 'PROBLEM_NOT_FOUND',
  PROBLEM_NOT_UPDATED = 'PROBLEM_NOT_UPDATED',
  PROBLEM_NOT_DELETED = 'PROBLEM_NOT_DELETED',
  NOT_ALLOWED_TO_CREATE_THE_PROBLEM = 'NOT_ALLOWED_TO_CREATE_THE_PROBLEM',
  NOT_ALLOWED_TO_VIEW_THE_PROBLEM = 'NOT_ALLOWED_TO_VIEW_THE_PROBLEM',
  NOT_ALLOWED_TO_UPDATE_THE_PROBLEM = 'NOT_ALLOWED_TO_UPDATE_THE_PROBLEM',
  NOT_ALLOWED_TO_DELETE_THE_PROBLEM = 'NOT_ALLOWED_TO_DELETE_THE_PROBLEM',
  PROBLEM_MODE_NOT_SUPPORTED = 'PROBLEM_MODE_NOT_SUPPORTED',
  PROBLEM_TYPE_NOT_SUPPORTED = 'PROBLEM_TYPE_NOT_SUPPORTED',
  PROBLEM_TIME_LIMIT_MUST_BE_A_NUMBER = 'PROBLEM_TIME_LIMIT_MUST_BE_A_NUMBER',
  PROBLEM_MEMORY_LIMIT_MUST_BE_NUMBER = 'PROBLEM_MEMORY_LIMIT_MUST_BE_NUMBER',
  TEST_CASE_FILE_EMPTY = 'TEST_CASE_FILE_EMPTY',
  // Contest errors
  INTERNAL_SERVER_ERROR_ON_CONTESTS_SERVICE = 'INTERNAL_SERVER_ERROR_ON_CONTESTS_SERVICE',
  CONTEST_NOT_CREATED = 'CONTEST_NOT_CREATED',
  CONTEST_NOT_FOUND = 'CONTEST_NOT_FOUND',
  CONTEST_NOT_UPDATED = 'CONTEST_NOT_UPDATED',
  CONTEST_NOT_DELETED = 'CONTEST_NOT_DELETED',
  NOT_ALLOWED_TO_CREATE_THE_CONTEST = 'NOT_ALLOWED_TO_CREATE_THE_CONTEST',
  NOT_ALLOWED_TO_VIEW_THE_CONTEST = 'NOT_ALLOWED_TO_VIEW_THE_CONTEST',
  NOT_ALLOWED_TO_UPDATE_THE_CONTEST = 'NOT_ALLOWED_TO_UPDATE_THE_CONTEST',
  NOT_ALLOWED_TO_DELETE_THE_CONTEST = 'NOT_ALLOWED_TO_DELETE_THE_CONTEST',
  NOT_ALLOWED_TO_REGISTER_TO_THE_CONTEST = 'NOT_ALLOWED_TO_REGISTER_TO_THE_CONTEST',
  IS_ALREADY_REGISTERED = 'IS_ALREADY_REGISTERED',
  NOT_ALLOWED_TO_VIEW_CONTESTS = 'NOT_ALLOWED_TO_VIEW_CONTESTS',
  SCOREBOARD_NOT_CREATED = 'SCOREBOARD_NOT_CREATED',
  SCOREBOARD_NOT_FOUND = 'SCOREBOARD_NOT_FOUND',
  SCOREBOARD_NOT_UPDATED = 'SCOREBOARD_NOT_UPDATED',
  SCOREBOARD_NOT_DELETED = 'SCOREBOARD_NOT_DELETED',
  NOT_ALLOWED_TO_CREATE_THE_SCOREBOARD = 'NOT_ALLOWED_TO_CREATE_THE_SCOREBOARD',
  NOT_ALLOWED_TO_VIEW_THE_SCOREBOARD = 'NOT_ALLOWED_TO_VIEW_THE_SCOREBOARD',
  NOT_ALLOWED_TO_UPDATE_THE_SCOREBOARD = 'NOT_ALLOWED_TO_UPDATE_THE_SCOREBOARD',
  NOT_ALLOWED_TO_DELETE_THE_SCOREBOARD = 'NOT_ALLOWED_TO_DELETE_THE_SCOREBOARD',
  CLARIFICATION_NOT_CREATED = 'CLARIFICATION_NOT_CREATED',
  CLARIFICATION_NOT_FOUND = 'CLARIFICATION_NOT_FOUND',
  CLARIFICATION_NOT_UPDATED = 'CLARIFICATION_NOT_UPDATED',
  CLARIFICATION_NOT_DELETED = 'CLARIFICATION_NOT_DELETED',
  NOT_ALLOWED_TO_SUBMIT_CLARIFICATION = 'NOT_ALLOWED_TO_SUBMIT_CLARIFICATION',
  NOT_ALLOWED_TO_VIEW_CLARIFICATION = 'NOT_ALLOWED_TO_VIEW_CLARIFICATION',
  NOT_ALLOWED_TO_UPDATE_CLARIFICATION = 'NOT_ALLOWED_TO_UPDATE_CLARIFICATION',
  NOT_ALLOWED_TO_DELETE_CLARIFICATION = 'NOT_ALLOWED_TO_DELETE_CLARIFICATION',
  // Submission errors
  INTERNAL_SERVER_ERROR_ON_SUBMISSIONS_SERVICE = 'INTERNAL_SERVER_ERROR_ON_SUBMISSIONS_SERVICE',
  SUBMISSION_NOT_FOUND = 'SUBMISSION_NOT_FOUND',
  SUBMISSION_NOT_CREATED = 'SUBMISSION_NOT_CREATED',
  SUBMISSION_NOT_UPDATED = 'SUBMISSION_NOT_UPDATED',
  SOURCE_EMPTY = 'SOURCE_EMPTY',
  PROGRAMMING_LANGUAGE_NOT_SUPPORTED = 'PROGRAMMING_LANGUAGE_NOT_SUPPORTED',
  NOT_ALLOWED_SUBMIT_THE_PROBLEM_IN_THE_CONTEST = 'NOT_ALLOWED_SUBMIT_THE_PROBLEM_IN_THE_CONTEST',
  JUDGEMENT_UNAVAILABLE = 'JUDGEMENT_UNAVAILABLE',
  // Utils errors
  INTERNAL_SERVER_ERROR_ON_UTILS_SERVICES = 'INTERNAL_SERVER_ERROR_ON_UTILS_SERVICES',
  EMPTY_IMAGE = 'EMPTY_IMAGE',
  CODES_ERROR = 'CODES_ERROR',
  COMPILATION_FAILED = 'COMPILATION_FAILED',
  FILES_ERROR = 'FILES_ERROR',
  THE_EMAIL_COULD_NOT_BE_SENT = 'THE_EMAIL_COULD_NOT_BE_SENT',
  // Team errors
  INTERNAL_SERVER_ERROR_ON_TEAMS_SERVICE = 'INTERNAL_SERVER_ERROR_ON_TEAMS_SERVICE',
  TEAM_NOT_CREATED = 'TEAM_NOT_CREATED',
  TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',
  TEAM_NOT_UPDATED = 'TEAM_NOT_UPDATED',
  TEAM_NOT_DELETED = 'TEAM_NOT_DELETED',
  NOT_ALLOWED_TO_CREATE_THE_TEAM = 'NOT_ALLOWED_TO_CREATE_THE_TEAM',
  NOT_ALLOWED_TO_VIEW_THE_TEAM = 'NOT_ALLOWED_TO_VIEW_THE_TEAM',
  NOT_ALLOWED_TO_UPDATE_THE_TEAM = 'NOT_ALLOWED_TO_UPDATE_THE_TEAM',
  NOT_ALLOWED_TO_DELETE_THE_TEAM = 'NOT_ALLOWED_TO_DELETE_THE_TEAM',
  TEAM_IS_REPORTED = 'TEAM_IS_REPORTED',
  TEAM_IS_ARCHIVED = 'TEAM_IS_ARCHIVED',
  // File errors
  INTERNAL_SERVER_ERROR_ON_FILES_SERVICE = 'INTERNAL_SERVER_ERROR_ON_FILES_SERVICE',
  FILE_NOT_CREATED = 'FILE_NOT_CREATED',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_NOT_UPDATED = 'FILE_NOT_UPDATED',
  FILE_NOT_DELETED = 'FILE_NOT_DELETED',
  NOT_ALLOWED_TO_CREATE_THE_FILE = 'NOT_ALLOWED_TO_CREATE_THE_FILE',
  NOT_ALLOWED_TO_VIEW_THE_FILE = 'NOT_ALLOWED_TO_VIEW_THE_FILE',
  NOT_ALLOWED_TO_UPDATE_THE_FILE = 'NOT_ALLOWED_TO_UPDATE_THE_FILE',
  NOT_ALLOWED_TO_DELETE_THE_FILE = 'NOT_ALLOWED_TO_DELETE_THE_FILE',
  FILE_IS_RESERVED = 'FILE_IS_RESERVED',
  FILE_IS_PRIVATE = 'FILE_IS_PRIVATE',
  FILE_IS_ARCHIVED = 'FILE_IS_ARCHIVED',
}

export type ApiError = {
  code: ErrorCode;
  detail: string;
  message: string;
};

export type ErrorResponse = {
  success: false;
  message: string;
  errors: ApiError[];
};

export type ContentResponse<T> = {
  success: true;
  message: string;
  content: T;
};

export type ContentsMeta = {
  page: number;
  size: number;
  totalElements: number;
  sort: { [key: string]: number }[];
  filter: Record<any, any>;
};

export type ContentsResponse<T> = {
  success: true;
  message: string;
  contents: T[];
  meta: ContentsMeta;
};

export enum LogLevel {
  FATAL = 'FATAL',
  ERROR = 'ERROR',
  WARN = 'WARN',
  INFO = 'INFO',
  DEBUG = 'DEBUG',
  TRACE = 'TRACE',
}

export enum HTTPMethod {
  POST = 'POST',
  GET = 'GET',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
}

export type RunnerNextRequest = { type: 'request'; body: string; method: HTTPMethod; url: string };

export type RunnerNextQueue = {
  type: 'queue';
  messageBody: string;
  messageGroupId: string;
  messageDeduplicationId: string;
};

export type RunnerNext = RunnerNextRequest | RunnerNextQueue;

export type RunCommand = {
  commandLine: string;
  inputFilePath: string;
  outputFilePath: string;
  errorFilePath: string;
  logFilePath: string;
  folderPath: string;
  timeLimit: number;
  memoryLimit: number;
  lockFilePath?: string;
  endFilePath?: string;
  rawExecution: boolean;
  isolated: boolean;
  next?: RunnerNext;
};

export type RunnerSQSMessageBody = {
  executions: RunCommand[];
  next?: RunnerNext;
};

export type Case = { caseKey: string; groups: number[] };

export type ProblemTestCase = { testCaseKey: string; groups: number[] };
export type ProblemSampleCase = { input: string; output: string };

// export type JudgingProblemDataType = {
//   problemId: string,
//   problemKey: string,
//   problemType: ProblemType,
//   problemTimeLimit: number,
//   problemMemoryLimit: number,
//   problemWithPE: boolean,
//   problemScoringMode: ProblemScoringMode,
//   problemPointsByGroups: ProblemSettingsPointsByGroups,
//   problemSampleCases: ProblemSampleCase[],
//   problemTestCases: ProblemTestCase[],
//   problemEvaluatorSource: string,
// }

// export type JudgingUserDataType = {
//   userId: string,
//   userNickname: string,
// }

// export type JudgingCompanyDataType = {
//   companyId: string,
//   // companyHighPerformanceRunnerTaskDefinition: string,
//   // companyHighPerformanceRunnerMinTasks: number,
//   // companyHighPerformanceRunnerMaxTasks: number,
//   // companyLowPerformanceRunnerTaskDefinition: string,
//   // companyLowPerformanceRunnerMinTasks: number,
//   // companyLowPerformanceRunnerMaxTasks: number,
// }

// export type JudgingContestDataType = {
//   contestId: string,
// }

export type JudgingFile = { language: CodeLanguage; fullFileName: string };
