export enum SocketBroadcastEvent {
  CODE_RUN_STATUS_NOTIFICATION = 'CODE_RUN_STATUS_NOTIFICATION',
  SUBMISSION_RUN_STATUS_NOTIFICATION = 'SUBMISSION_RUN_STATUS_NOTIFICATION',
  USER_NOTIFICATION = 'USER_NOTIFICATION',
}

export enum SocketActionEvent {
  PING = 'PING',
  
  SUBSCRIBE_CODE_RUN_STATUS = 'SUBSCRIBE_CODE_RUN_STATUS',
  UNSUBSCRIBE_CODE_RUN_STATUS = 'UNSUBSCRIBE_CODE_RUN_STATUS',
  
  SUBSCRIBE_SUBMISSION_RUN_STATUS = 'SUBSCRIBE_SUBMISSION_RUN_STATUS',
  UNSUBSCRIBE_SUBMISSION_RUN_STATUS = 'UNSUBSCRIBE_SUBMISSION_RUN_STATUS',
}

export enum SocketResponseEvent {
  PONG = 'PONG',
  CODE_RUN_STATUS_MESSAGE = 'CODE_RUN_STATUS_MESSAGE',
  SUBMISSION_RUN_STATUS_MESSAGE = 'SUBMISSION_RUN_STATUS_MESSAGE',
  USER_MESSAGE = 'USER_MESSAGE',
}
