import { ObjectIdType } from './commons';

export enum WebSocketBroadcastEvent {
  PING = 'PING',
  CODE_RUN_STATUS_NOTIFICATION = 'CODE_RUN_STATUS_NOTIFICATION',
  SUBMISSION_RUN_STATUS_NOTIFICATION = 'SUBMISSION_RUN_STATUS_NOTIFICATION',
  USER_NOTIFICATION = 'USER_NOTIFICATION',
}

export enum WebSocketActionEvent {
  PING = 'PING',
  
  AUTHENTICATE = 'AUTHENTICATE',
  
  SUBSCRIBE_CODE_RUN_STATUS = 'SUBSCRIBE_CODE_RUN_STATUS',
  UNSUBSCRIBE_CODE_RUN_STATUS = 'UNSUBSCRIBE_CODE_RUN_STATUS',
  
  SUBSCRIBE_SUBMISSION_RUN_STATUS = 'SUBSCRIBE_SUBMISSION_RUN_STATUS',
  UNSUBSCRIBE_SUBMISSION_RUN_STATUS = 'UNSUBSCRIBE_SUBMISSION_RUN_STATUS',
  
  SUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITIONS_LIST = 'SUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITIONS_LIST',
  UNSUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITIONS_LIST = 'UNSUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITIONS_LIST',
  
  SUBSCRIBE_SEND_DATA_ECS_TASKS_LIST = 'SUBSCRIBE_SEND_DATA_ECS_TASKS_LIST',
  UNSUBSCRIBE_SEND_DATA_ECS_TASKS_LIST = 'UNSUBSCRIBE_SEND_DATA_ECS_TASKS_LIST',
  
  SUBSCRIBE_SEND_DATA_EC2_INSTANCES_LIST = 'SUBSCRIBE_SEND_DATA_EC2_INSTANCES_LIST',
  UNSUBSCRIBE_SEND_DATA_EC2_INSTANCES_LIST = 'UNSUBSCRIBE_SEND_DATA_EC2_INSTANCES_LIST',
  
  SUBSCRIBE_SEND_DATA_SSM_SESSIONS_LIST = 'SUBSCRIBE_SEND_DATA_SSM_SESSIONS_LIST',
  UNSUBSCRIBE_SEND_DATA_SSM_SESSIONS_LIST = 'UNSUBSCRIBE_SEND_DATA_SSM_SESSIONS_LIST',
  
  SUBSCRIBE_PROBLEM_CRAWLED = 'SUBSCRIBE_PROBLEM_CRAWLED',
  UNSUBSCRIBE_PROBLEM_CRAWLED = 'UNSUBSCRIBE_PROBLEM_CRAWLED',
}

export enum WebSocketResponseEvent {
  PONG = 'PONG',
  RESPONSE = 'RESPONSE',
  CODE_RUN_STATUS_MESSAGE = 'CODE_RUN_STATUS_MESSAGE',
  SUBMISSION_RUN_STATUS_MESSAGE = 'SUBMISSION_RUN_STATUS_MESSAGE',
  USER_MESSAGE = 'USER_MESSAGE',
  SEND_DATA_ECS_TASK_DEFINITIONS_LIST = 'SEND_DATA_ECS_TASK_DEFINITIONS_LIST',
  SEND_DATA_ECS_TASKS_LIST = 'SEND_DATA_ECS_TASKS_LIST',
  SEND_DATA_EC2_INSTANCES_LIST = 'SEND_DATA_EC2_INSTANCES_LIST',
  SEND_DATA_SSM_SESSIONS_LIST = 'SEND_DATA_SSM_SESSIONS_LIST',
  PROBLEM_CRAWLED = 'PROBLEM_CRAWLED',
}

export type WebSocketResponseEventKey = `${WebSocketResponseEvent}-${ObjectIdType}-${string}`;
