import { ObjectIdType } from './commons';

export enum WebSocketBroadcastEvent {
  PING = 'PING',
  CODE_RUN_STATUS_NOTIFICATION = 'CODE_RUN_STATUS_NOTIFICATION',
  SUBMISSION_RUN_STATUS_NOTIFICATION = 'SUBMISSION_RUN_STATUS_NOTIFICATION',
  USER_NOTIFICATION = 'USER_NOTIFICATION',
}

export enum WebSocketActionEvent {
  PING = 'PING',
  
  AUTHENTICATE = 'AUTHENTICATE',
  
  SUBSCRIBE_CODE_RUN_STATUS = 'SUBSCRIBE_CODE_RUN_STATUS',
  UNSUBSCRIBE_CODE_RUN_STATUS = 'UNSUBSCRIBE_CODE_RUN_STATUS',
  
  SUBSCRIBE_SUBMISSION_RUN_STATUS = 'SUBSCRIBE_SUBMISSION_RUN_STATUS',
  UNSUBSCRIBE_SUBMISSION_RUN_STATUS = 'UNSUBSCRIBE_SUBMISSION_RUN_STATUS',
  
  SUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITION_LIST = 'SUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITION_LIST',
  UNSUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITION_LIST = 'UNSUBSCRIBE_SEND_DATA_ECS_TASK_DEFINITION_LIST',
}

export enum WebSocketResponseEvent {
  PONG = 'PONG',
  CODE_RUN_STATUS_MESSAGE = 'CODE_RUN_STATUS_MESSAGE',
  SUBMISSION_RUN_STATUS_MESSAGE = 'SUBMISSION_RUN_STATUS_MESSAGE',
  USER_MESSAGE = 'USER_MESSAGE',
  SEND_DATA_ECS_TASK_DEFINITION_LIST = 'SEND_DATA_ECS_TASK_DEFINITION_LIST',
  SEND_DATA_ECS_TASK_LIST = 'SEND_DATA_ECS_TASK_LIST',
}

export type WebSocketResponseEventKey = `${WebSocketResponseEvent}-${ObjectIdType}-${string}`;
