export const ContestEventAction = {
  DATA_UPDATE: 'DATA_UPDATE',
  SCOREBOARD_RECALCULATE: 'SCOREBOARD_RECALCULATE',
  SCOREBOARD_UNLOCK: 'SCOREBOARD_UNLOCK',
  SCOREBOARD_LOCK: 'SCOREBOARD_LOCK',
  ENABLE_UPSOLVING: 'ENABLE_UPSOLVING',
  DISABLE_UPSOLVING: 'DISABLE_UPSOLVING',
  PARTICIPANT_JOIN: 'PARTICIPANT_JOIN',
} as const;

export type ContestEventAction = (typeof ContestEventAction)[keyof typeof ContestEventAction];
