export const WebSocketSubscriptionEvent = {
  SUBSCRIBE_CODE_RUN_STATUS: 'SUBSCRIBE_CODE_RUN_STATUS',
  UNSUBSCRIBE_CODE_RUN_STATUS: 'UNSUBSCRIBE_CODE_RUN_STATUS',

  SUBSCRIBE_SUBMISSION_RUN_STATUS: 'SUBSCRIBE_SUBMISSION_RUN_STATUS',
  UNSUBSCRIBE_SUBMISSION_RUN_STATUS: 'UNSUBSCRIBE_SUBMISSION_RUN_STATUS',

  SUBSCRIBE_GET_DATA: 'SUBSCRIBE_GET_DATA',
  UNSUBSCRIBE_GET_DATA: 'SUBSCRIBE_GET_DATA',

  SUBSCRIBE_PROBLEM_CRAWLED: 'SUBSCRIBE_PROBLEM_CRAWLED',
  UNSUBSCRIBE_PROBLEM_CRAWLED: 'UNSUBSCRIBE_PROBLEM_CRAWLED',

  SUBSCRIBE_SUBMISSIONS_CRAWL: 'SUBSCRIBE_SUBMISSIONS_CRAWL',
  UNSUBSCRIBE_SUBMISSIONS_CRAWL: 'UNSUBSCRIBE_SUBMISSIONS_CRAWL',

  SUBSCRIBE_CONTEST_CHANGES: 'SUBSCRIBE_CONTEST_CHANGES',
  UNSUBSCRIBE_CONTEST_CHANGES: 'UNSUBSCRIBE_CONTEST_CHANGES',

  SUBSCRIBE_CLIENT_TRACK: 'SUBSCRIBE_CLIENT_TRACK',
  UNSUBSCRIBE_CLIENT_TRACK: 'UNSUBSCRIBE_CLIENT_TRACK',

  SUBSCRIBE_USER_NOTIFICATION: 'SUBSCRIBE_USER_NOTIFICATION',
  UNSUBSCRIBE_USER_NOTIFICATION: 'UNSUBSCRIBE_USER_NOTIFICATION',
} as const;

export type WebSocketSubscriptionEvent = (typeof WebSocketSubscriptionEvent)[keyof typeof WebSocketSubscriptionEvent];
