export const WebSocketResponseEvent = {
  PONG: 'PONG',
  CODE_RUN_STATUS: 'CODE_RUN_STATUS',
  SUBMISSION_RUN_STATUS: 'SUBMISSION_RUN_STATUS',
  USER_MESSAGE: 'USER_MESSAGE',
  SEND_DATA: 'SEND_DATA',
  SEND_DATA_ECS_TASK_DEFINITIONS_LIST: 'SEND_DATA_ECS_TASK_DEFINITIONS_LIST',
  SEND_DATA_ECS_TASKS_LIST: 'SEND_DATA_ECS_TASKS_LIST',
  SEND_DATA_EC2_INSTANCES_LIST: 'SEND_DATA_EC2_INSTANCES_LIST',
  SEND_DATA_SSM_SESSIONS_LIST: 'SEND_DATA_SSM_SESSIONS_LIST',
  SEND_DATA_RUN_COMMAND: 'SEND_DATA_RUN_COMMAND',
  SEND_DATA_CLIENT_TRACK: 'SEND_DATA_CLIENT_TRACK',
  SEND_DATA_CHAT_COMPLETIONS: 'SEND_DATA_CHAT_COMPLETIONS',
  PROBLEM_CRAWLED: 'PROBLEM_CRAWLED',
  SUBMISSIONS_CRAWL: 'SUBMISSIONS_CRAWL',
  CONTEST_CHANGES: 'CONTEST_CHANGES',
  CLIENT_TRACK: 'CLIENT_TRACK',
  USER_NOTIFICATION: 'USER_NOTIFICATION',
  USER_NOTIFICATION_SUBMISSION: 'USER_NOTIFICATION_SUBMISSION',
  USER_NOTIFICATION_CONTEST_CLARIFICATION: 'USER_NOTIFICATION_CONTEST_CLARIFICATION',
} as const;

export type WebSocketResponseEvent = (typeof WebSocketResponseEvent)[keyof typeof WebSocketResponseEvent];
